<?php

namespace Database\Seeders;

use App\Models\Jadwal_Kuliah;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class jadwalkuliahseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jdwl_kul = [
            [
                'id' => '1',
                'ruang_kuliah_kode_ruang' => 'E101',
                'mata_kuliah_kode_mk' => 'Paik101',
                'hari' => 'Senin',
                'kelas' => 'A',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '2',
                'ruang_kuliah_kode_ruang' => 'E102',
                'mata_kuliah_kode_mk' => 'Paik101',
                'hari' => 'Selasa',
                'kelas' => 'B',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',

            ],
            [
                'id' => '3',
                'ruang_kuliah_kode_ruang' => 'E103',
                'mata_kuliah_kode_mk' => 'Paik101',
                'hari' => 'Rabu',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '4',
                'ruang_kuliah_kode_ruang' => 'E104',
                'mata_kuliah_kode_mk' => 'Paik101',
                'hari' => 'Kamis',
                'kelas' => 'D',
                'jam_mulai' => '10:00',
                'jam_selesai' => '13:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '5',
                'ruang_kuliah_kode_ruang' => 'E105',
                'mata_kuliah_kode_mk' => 'Paik102',
                'hari' => 'Jumat',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '6',
                'ruang_kuliah_kode_ruang' => 'E105',
                'mata_kuliah_kode_mk' => 'Paik102',
                'hari' => 'Senin',
                'kelas' => 'B',
                'jam_mulai' => "11:00", // Format waktu diperbaiki
                'jam_selesai' => "12:00", // Format waktu diperbaiki
                'status' => 'diajukan',
            ],
            [
                'id' => '7',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik102',
                'hari' => 'Selasa',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '8',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik102',
                'hari' => 'Rabu',
                'kelas' => 'D',
                'jam_mulai' => '10:00',
                'jam_selesai' => '13:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '9',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik103',
                'hari' => 'Kamis',
                'kelas'=> 'A',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '10',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik103',
                'hari' => 'Jumat',
                'kelas'=> 'B',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '11',
                'ruang_kuliah_kode_ruang' => 'E205',
                'mata_kuliah_kode_mk' => 'Paik103',
                'hari' => 'Senin',
                'kelas'=> 'C',
                'jam_mulai' => '15:00',
                'jam_selesai' => '18:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '12',
                'ruang_kuliah_kode_ruang' => 'E205',
                'mata_kuliah_kode_mk' => 'Paik103',
                'hari' => 'Selasa',
                'kelas'=> 'D',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '13',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik104',
                'hari' => 'Rabu',
                'kelas'=> 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '14',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik104',
                'hari' => 'Kamis',
                'kelas'=> 'B',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '15',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik104',
                'hari' => 'Jumat',
                'kelas'=> 'C',
                'jam_mulai' => '10:00',
                'jam_selesai' => '13:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '16',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik104',
                'hari' => 'Senin',
                'kelas'=> 'D',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '17',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik090',
                'hari' => 'Senin',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '18',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik090',
                'hari' => 'Senin',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '19',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik090',
                'hari' => 'Senin',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '20',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik090',
                'hari' => 'Senin',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '21',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik091',
                'hari' => 'Selasa',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '22',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik091',
                'hari' => 'Selasa',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '23',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik091',
                'hari' => 'Selasa',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '24',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik091',
                'hari' => 'Selasa',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '25',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik092',
                'hari' => 'Rabu',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '26',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik092',
                'hari' => 'Rabu',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '27',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik092',
                'hari' => 'Rabu',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '28',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik092',
                'hari' => 'Rabu',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '29',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik093',
                'hari' => 'Kamis',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '30',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik093',
                'hari' => 'Kamis',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '31',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik093',
                'hari' => 'Kamis',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '32',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik093',
                'hari' => 'Kamis',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '33',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik094',
                'hari' => 'Jumat',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '34',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik094',
                'hari' => 'Jumat',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '35',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik094',
                'hari' => 'Jumat',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '36',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik094',
                'hari' => 'Jumat',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '37',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik095',
                'hari' => 'Sabtu',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '38',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik095',
                'hari' => 'Sabtu',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '39',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik095',
                'hari' => 'Sabtu',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '40',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik095',
                'hari' => 'Sabtu',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            // [
            //     'id' => '41',
            //     'ruang_kuliah_kode_ruang' => 'E201',
            //     'mata_kuliah_kode_mk' => 'Paik096',
            //     'hari' => 'Minggu',
            //     'kelas' => 'A',
            //     'jam_mulai' => '08:00',
            //     'jam_selesai' => '11:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '42',
            //     'ruang_kuliah_kode_ruang' => 'E202',
            //     'mata_kuliah_kode_mk' => 'Paik096',
            //     'hari' => 'Minggu',
            //     'kelas' => 'B',
            //     'jam_mulai' => '11:00',
            //     'jam_selesai' => '14:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '43',
            //     'ruang_kuliah_kode_ruang' => 'E203',
            //     'mata_kuliah_kode_mk' => 'Paik096',
            //     'hari' => 'Minggu',
            //     'kelas' => 'C',
            //     'jam_mulai' => '13:00',
            //     'jam_selesai' => '16:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '44',
            //     'ruang_kuliah_kode_ruang' => 'E204',
            //     'mata_kuliah_kode_mk' => 'Paik096',
            //     'hari' => 'Minggu',
            //     'kelas' => 'D',
            //     'jam_mulai' => '16:00',
            //     'jam_selesai' => '19:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '45',
            //     'ruang_kuliah_kode_ruang' => 'E201',
            //     'mata_kuliah_kode_mk' => 'Paik097',
            //     'hari' => 'Senin',
            //     'kelas' => 'A',
            //     'jam_mulai' => '08:00',
            //     'jam_selesai' => '11:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '46',
            //     'ruang_kuliah_kode_ruang' => 'E202',
            //     'mata_kuliah_kode_mk' => 'Paik097',
            //     'hari' => 'Senin',
            //     'kelas' => 'B',
            //     'jam_mulai' => '11:00',
            //     'jam_selesai' => '14:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '47',
            //     'ruang_kuliah_kode_ruang' => 'E203',
            //     'mata_kuliah_kode_mk' => 'Paik097',
            //     'hari' => 'Senin',
            //     'kelas' => 'C',
            //     'jam_mulai' => '13:00',
            //     'jam_selesai' => '16:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '48',
            //     'ruang_kuliah_kode_ruang' => 'E204',
            //     'mata_kuliah_kode_mk' => 'Paik097',
            //     'hari' => 'Senin',
            //     'kelas' => 'D',
            //     'jam_mulai' => '16:00',
            //     'jam_selesai' => '19:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '49',
            //     'ruang_kuliah_kode_ruang' => 'E201',
            //     'mata_kuliah_kode_mk' => 'Paik098',
            //     'hari' => 'Selasa',
            //     'kelas' => 'A',
            //     'jam_mulai' => '08:00',
            //     'jam_selesai' => '11:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '50',
            //     'ruang_kuliah_kode_ruang' => 'E202',
            //     'mata_kuliah_kode_mk' => 'Paik098',
            //     'hari' => 'Selasa',
            //     'kelas' => 'B',
            //     'jam_mulai' => '11:00',
            //     'jam_selesai' => '14:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '51',
            //     'ruang_kuliah_kode_ruang' => 'E203',
            //     'mata_kuliah_kode_mk' => 'Paik098',
            //     'hari' => 'Selasa',
            //     'kelas' => 'C',
            //     'jam_mulai' => '13:00',
            //     'jam_selesai' => '16:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '52',
            //     'ruang_kuliah_kode_ruang' => 'E204',
            //     'mata_kuliah_kode_mk' => 'Paik098',
            //     'hari' => 'Selasa',
            //     'kelas' => 'D',
            //     'jam_mulai' => '16:00',
            //     'jam_selesai' => '19:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '53',
            //     'ruang_kuliah_kode_ruang' => 'E201',
            //     'mata_kuliah_kode_mk' => 'Paik099',
            //     'hari' => 'Rabu',
            //     'kelas' => 'A',
            //     'jam_mulai' => '08:00',
            //     'jam_selesai' => '11:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '54',
            //     'ruang_kuliah_kode_ruang' => 'E202',
            //     'mata_kuliah_kode_mk' => 'Paik099',
            //     'hari' => 'Rabu',
            //     'kelas' => 'B',
            //     'jam_mulai' => '11:00',
            //     'jam_selesai' => '14:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '55',
            //     'ruang_kuliah_kode_ruang' => 'E203',
            //     'mata_kuliah_kode_mk' => 'Paik099',
            //     'hari' => 'Rabu',
            //     'kelas' => 'C',
            //     'jam_mulai' => '13:00',
            //     'jam_selesai' => '16:00',
            //     'status' => 'diajukan',
            // ],
            // [
            //     'id' => '56',
            //     'ruang_kuliah_kode_ruang' => 'E204',
            //     'mata_kuliah_kode_mk' => 'Paik099',
            //     'hari' => 'Rabu',
            //     'kelas' => 'D',
            //     'jam_mulai' => '16:00',
            //     'jam_selesai' => '19:00',
            //     'status' => 'diajukan',
            // ],
            [
                'id' => '69',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik105',
                'hari' => 'Senin',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '70',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik105',
                'hari' => 'Senin',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '71',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik105',
                'hari' => 'Senin',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '72',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik105',
                'hari' => 'Senin',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '73',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik106',
                'hari' => 'Selasa',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '74',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik106',
                'hari' => 'Selasa',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '75',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik106',
                'hari' => 'Selasa',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '76',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik106',
                'hari' => 'Selasa',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '77',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik107',
                'hari' => 'Rabu',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '78',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik107',
                'hari' => 'Rabu',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '79',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik107',
                'hari' => 'Rabu',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '80',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik107',
                'hari' => 'Rabu',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '81',
                'ruang_kuliah_kode_ruang' => 'E201',
                'mata_kuliah_kode_mk' => 'Paik108',
                'hari' => 'Kamis',
                'kelas' => 'A',
                'jam_mulai' => '08:00',
                'jam_selesai' => '11:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '82',
                'ruang_kuliah_kode_ruang' => 'E202',
                'mata_kuliah_kode_mk' => 'Paik108',
                'hari' => 'Kamis',
                'kelas' => 'B',
                'jam_mulai' => '11:00',
                'jam_selesai' => '14:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '83',
                'ruang_kuliah_kode_ruang' => 'E203',
                'mata_kuliah_kode_mk' => 'Paik108',
                'hari' => 'Kamis',
                'kelas' => 'C',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:00',
                'status' => 'diajukan',
            ],
            [
                'id' => '84',
                'ruang_kuliah_kode_ruang' => 'E204',
                'mata_kuliah_kode_mk' => 'Paik108',
                'hari' => 'Kamis',
                'kelas' => 'D',
                'jam_mulai' => '16:00',
                'jam_selesai' => '19:00',
                'status' => 'diajukan',
            ],

           
            ];
            foreach ($jdwl_kul as $key=>$val) {
                Jadwal_Kuliah::create($val); // Menggunakan model yang benar
            }
    }
}
